### PR TITLE
Revert data loading portion of azavea.opentripplaner role

### PR DESCRIPTION
**Pull request by CloudNiner**
Leave data loading for the user to configure

Do not do any data loading in this role, because:
- More extensible: The user is in control of their data sources,
  no need to depend on this playbook not supporting a data source
  available in OTP
- The GTFS download process generally requires agreement to licenses,
  and so files or links should not be distrubuted here. Skipping GTFS
  data in the import process make overridding creation of the
  data-config.xml in a child role difficult, since the xml file needs
  to be modified at that time

TODO: Provide sample data-config.xml + data role in a different
repository?

### CODE REVIEW

**Comment by CloudNiner** [comment]
@hectcastro probably want to take a brief look as well

**Comment by hectcastro** [comment]
Sorry for being late. Everything here looks good to me. Great detail in the `README`.

**Comment by hectcastro** [comment]
@CloudNiner Did you want to cut another release with these changes now?

**Comment by CloudNiner** [comment]
Yeah, just pushed a release/0.2.0 branch.

**Pull request merged**
