### PR TITLE
Enable OTP analyst

### PR DESCRIPTION
**Pull request by moradology**

### CODE REVIEW

**Comment by CloudNiner** [comment]
I was thinking about making this a configurable option. Thoughts?

**Comment by flibbertigibbet** [comment]
I don't know why it's not enabled by default; I don't think there's much cost to having analyst running.

**Comment by CloudNiner** [comment]
Cool works for me.

+1

**Comment by CloudNiner** [comment]
Merge and then I'll cut the release and update on ansible galaxy, and then submit a PR for CAC to bump versions.

**Pull request merged**
